### ISSUE TITLE
Demo input data?

### ISSUE THREAD

**Issue by BinhongLiu** [wilkinsonlab/robust-clustering-metagenomics#1]
Hi Pro.,
    It's really a nice function you developed for the microbiome data analysis. There were some errors when I performed the analysis. 

 setwd("D:/stat")
> load('D:/stat/hongbinliu.RData')
> list.results <- robust.clustering(data.norm,"Day","hongbin")
 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘distance’ for signature ‘"otu_table", "missing"’ 
4.
stop(gettextf("unable to find an inherited method for function %s for signature %s", 
    sQuote(fdef@generic), sQuote(cnames)), domain = NA) 
3.
(function (classes, fdef, mtable) 
{
    methods <- .findInheritedMethods(classes, fdef, mtable)
    if (length(methods) == 1L)  ... 
2.
distance(otu_table(data.norm), method = distanceMethod) at robust.clustering.metagenomics.functions.r#581
1.
robust.clustering(data.norm, "Day", "hongbin") 

Could you help me with this error, please? Besides, would you provide the demo input data in the paper if it convenient?
Thanks!
hongbin liu

**Comment by beatrizgj** [comment]
Thanks for your email and your interest in our software.
You can check the data in the associated zenodo: https://zenodo.org/record/1485916
I hope it helps!

**Comment by BinhongLiu** [comment]
hi，
    I’ve checked the zenodo but it seems that only the output files from the analysis are uploaded there, but not the input files. If it’s convenient, could you send me the demo input files, please?
Thank you for your kind help!
Best wishes!
Hongbin Liu.

发自我的iPad

**Comment by beatrizgj** [comment]
Hi,
you should find the input files in the original publications, given that we are not the owner of those data.

In addition, you could check this input file from a different and newer repository where we use our robust clustering algorithm: https://github.com/beatrizgj/MDPbiomeGEM/blob/master/Src/DockerMDPbiome/CommunityExample/data.norm.sub_phyloseqObject.RData

and/or run it using the fragments of this notebook where robust clustering is run: 
https://github.com/beatrizgj/MDPbiomeGEM/blob/master/Src/DockerMDPbiome/config_MDPbiome_template.ipynb

In fact, that repository describe a available docker image (docker pull beatrizgj/mdpbiome) where the robust clustering algorithm could be run. See the detailed instructions in https://github.com/beatrizgj/MDPbiomeGEM

I hope it helps!

Good luck

**Comment by BinhongLiu** [comment]
Hi,   
Thank you so much for your reply! I just performed the analysis successfully using the script https://github.com/beatrizgj/MDPbiomeGEM/blob/master/Src/DockerMDPbiome/CommunityExample/data.norm.sub_phyloseqObject.RData. It's really helpful for me. Thank you again!

 Best wishes!

Hongbin Liu

**Comment by beatrizgj** [comment]
Great!
I'm happy you could perform the analysis.
